version : 1
database: sqlite:///:memory:
files:
    - path: sample_server.log
      patterns:
          - regex: ([0-9.]+) ([0-9:]+) \[([^\]]+)\] ([^ ]+)[^:]*: (.*)
            fields: [ date, time, user, recipient, message ]
            datetime-format: %Y/%m/%d %H:%M:%S
            tests:
                - 2013.01.01 00:00:00 UserA -> UserB: singleword!
                - 2013.01.01 10:00:00 UserA -> UserB: multi word!
    - path: sample_apache.log
      patterns:
          - regex: ([0-9.]+) [^ ]+ ([^ ]+) \[([^ ]+) [^\]]+\] "([A-Z]+) ([^"]+)" ("[^"]+") ("[^"]+")
            fields: [ ip, user, datetime, method, path ]
            datetime-format: %d/%b/%Y:%H:%M:%S
            tests:
                - 10.0.0.1 - admin [01/Jan/2013:00:00:00 -0500] "GET /" 200 100 "http://example.com/" "Mozilla/5.0 (Windows NT 6.0; rv:19.0) Gecko/20100101 Firefox/19.0"
